accounts/urls.py
from django.urls import path
from . import views
from .views import logout_view


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.list_projects, name="list_projects"),
    path("<int:id>/", views.show_project, name="show_project"),
    path("create/", views.create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from . import views
from .views import ShowMyTasksView

urlpatterns = [
    path("create/", views.create_task, name="create_task"),
    path("mine/", ShowMyTasksView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "projects/",
        include("projects.urls"),
    ),
    path(
        "accounts/",
        include("accounts.urls"),
    ),
    path("tasks/", include("tasks.urls")),
    path("", views.redirect_to_projects, name="home"),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )
    members = models.ManyToManyField(
        User, related_name="member_of", blank=True
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="tasks"
    )

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput
    )

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["is_completed"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import LoginForm, SignupForm


def login_view(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "accounts/login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("list_projects"))
        return render(
            request,
            "accounts/login.html",
            {"form": form, "error_message": "Invalid credentials"},
        )


def logout_view(request):
    logout(request)
    return redirect("login")


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password != password_confirmation:
                error_message = "The passwords do not match"
                return render(
                    request,
                    "accounts/signup.html",
                    {"form": form, "error_message": error_message},
                )

            # Create a new user account
            user = User.objects.create_user(
                username=username, password=password
            )

            # Log in the user
            login(request, user)

            return redirect(reverse("list_projects"))
    else:
        form = SignupForm()

    return render(request, "accounts/signup.html", {"form": form})

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project
from django.contrib.auth.decorators import login_required
from .forms import ProjectForm


@login_required
def list_projects(request):
    projects = Project.objects.filter(owner=request.user)
    context = {"projects": projects}
    return render(request, "projects/project_list.html", context)


def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    context = {"project": project}
    return render(request, "projects/project_detail.html", context)


def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm()

    return render(request, "projects/create_project.html", {"form": form})

tasks/views.py
from django.shortcuts import render, redirect
from .forms import TaskForm
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView


def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = TaskForm()

    return render(request, "tasks/create_task.html", {"form": form})


class ShowMyTasksView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/show_my_tasks.html"
    context_object_name = "tasks"

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(assignee=user)

tracker/views.py
from django.shortcuts import redirect


def redirect_to_projects(request):
    return redirect("list_projects")

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>Login</h1>
        <form method="post" action="{% url 'login' %}">
          {{ form }}
          <button type="submit">Login</button>
        </form>
      </div>
    </main>
  </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
  <head>
    <title>Signup</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>Signup</h1>
        <form method="post" action="{% url 'signup' %}">
          {% csrf_token %} {{ form }}
          <button type="submit">Signup</button>
        </form>
      </div>
    </main>
  </body>
</html>

projects/templates/projects/create_project.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Create Project</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>Create a new project</h1>
        <form method="post" action="{% url 'create_project' %}">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

projects/templates/projects/project_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Project Detail</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>{{ project.name }}</h1>
        <p>{{ project.description }}</p>
        <h2>Tasks</h2>
        <p><a href="{% url 'create_task' %}">Create a new task</a></p>
        {% if project.tasks.all %}
        <table>
          <tr>
            <th>Name</th>
            <th>Assignee</th>
            <th>Start date</th>
            <th>Due date</th>
            <th>Is completed</th>
          </tr>
          {% for task in project.tasks.all %}
          <tr>
            <td>{{ task.name }}</td>
            <td>{{ task.assignee.username }}</td>
            <td>{{ task.start_date }}</td>
            <td>{{ task.due_date }}</td>
            <td>{{ task.is_completed|yesno:"yes,no" }}</td>
          </tr>
          {% endfor %}
        </table>
        {% else %}
        <p>This project has no tasks</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>

projects/templates/projects/project_list.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Project List</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>My Projects</h1>
        <p><a href="{% url 'create_project' %}">Create a new project</a></p>
        {% if projects %}
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Number of tasks</th>
            </tr>
          </thead>
          <tbody>
            {% for project in projects %}
            <tr>
              <td>
                <a href="{% url 'show_project' project.id %}"
                  >{{ project.name }}</a
                >
              </td>
              <td>{{ project.tasks.all|length }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>You are not assigned to any projects</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>

tasks/templates/tasks/create_task.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Task</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <div>
        <h1>Create a new task</h1>
        <form method="post">
          {% csrf_token %}
          <div>
            <label for="id_name">Name:</label>
            <input
              type="text"
              id="id_name"
              name="name"
              maxlength="200"
              required
            />
          </div>
          <div>
            <label for="id_start_date">Start Date:</label>
            <input
              type="datetime-local"
              id="id_start_date"
              name="start_date"
              required
            />
          </div>
          <div>
            <label for="id_due_date">Due Date:</label>
            <input
              type="datetime-local"
              id="id_due_date"
              name="due_date"
              required
            />
          </div>
          <div>
            <label for="id_project">Project:</label>
            <select id="id_project" name="project" required>
              {% for project in projects %}
              <option value="{{ project.id }}">{{ project.name }}</option>
              {% endfor %}
            </select>
          </div>
          <div>
            <label for="id_assignee">Assignee:</label>
            <select id="id_assignee" name="assignee" required>
              {% for user in users %}
              <option value="{{ user.id }}">{{ user.username }}</option>
              {% endfor %}
            </select>
          </div>
          <button type="submit">Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

tasks/templates/tasks/show_my_tasks.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Tasks</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
          <li><a href="{% url 'list_projects' %}">My projects</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <h1>My Tasks</h1>
        {% if tasks %}
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Start date</th>
              <th>Due date</th>
              <th>Is completed</th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
            <tr>
              <td>{{ task.name }}</td>
              <td>{{ task.start_date }}</td>
              <td>{{ task.due_date }}</td>
              <td>{{ task.is_completed|yesno:"yes,no" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>You have no tasks</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>